### ISSUE TITLE
Kvantum: Qogir-dark-solid is not a Kvantum theme folder

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-kde#12]
[Title.](https://i.imgur.com/JTbvLIU.png)

**Comment by Kodehawa** [comment]
Fixed it myself by renaming the files of the folder to Qogir-dark-solid.kvtheme and Qogir-dark-solid.svg

**Comment by Kodehawa** [comment]
This is still an issue.

**Comment by vinceliuice** [comment]
Didn't notice this, I'll fix it

**Comment by Kodehawa** [comment]
Thanks. Been fixed on dfd4e92165f7d4506b73f4c3e7ce80dd208f3e9d
