### ISSUE TITLE
Inaccurate panel coloring

### ISSUE THREAD

**Issue by talesaraujo** [vinceliuice/Qogir-kde#16]
_Note: This was already mentioned at the KDE store, but I chose to do it formally here as well._

There's a minor issue concerning the panel color styling - it seems to affect both Light and Dark variants: assuming we have three opened windows, and proceed to minimize the active one, we no longer have track of the bottom mark (the blue color disappears), whereas the ones that are in background remain gray (an expected behavior). I suppose it should be colored with a gray color as well (or at least something else), since the application is still running, otherwise we couldn't keep track of what's actually running just by looking the panel.

| ![01](https://user-images.githubusercontent.com/23703961/74080925-9445be00-4a27-11ea-89bb-5155138793a5.png) | 
| :--: |
| *Before* |

| ![02](https://user-images.githubusercontent.com/23703961/74080933-b2132300-4a27-11ea-82f8-420a4bd40f0f.png) |
| :--: |
| *After* |

**Comment by vinceliuice** [comment]
You are right! I'll fix this.

**Comment by vinceliuice** [comment]
I updated the style

**Comment by talesaraujo** [comment]
Thanks a lot. 
Been fixed on commit https://github.com/vinceliuice/Qogir-kde/commit/d86e364b2252444344ef85064d482b33909d2e17
