### ISSUE TITLE
Aurorae theme title text color doesn't match the GNOME theme counterpart.

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-kde#17]
Title. To match the GNOME titlebar color the ActiveTextColor in the aurorae themes (both dark circle and dark normal) should be 201,208,216,215 

Pretty much that, it just bothers me a little.

**Comment by vinceliuice** [comment]
Thanks! I'll fix this

**Comment by Kodehawa** [comment]
Thanks. Was fixed on https://github.com/vinceliuice/Qogir-kde/commit/634265d51c44e13c24d3cd0569a3b3dbc45fe2db :D

**Comment by Kodehawa** [comment]
Sorry. I tested it further and it should be 
ActiveTextColor=177,178,183,255

Having transparency on it seems to break aurorae and it makes the whole text transparent, that was my bad.

Inactive color might be
InactiveTextColor=138,143,152,255

but am not 100% sure, you could double check.

**Comment by vinceliuice** [comment]
OK! I'll adjust this

**Comment by Kodehawa** [comment]
Yeah, that fixes the transparency issue. I gave you another set of colors you can try up there, without transparency those are the ones that look closer to the Mutter theme IMO. 

Of course, you can test around too.

Thanks for the amazing theme btw and I hope you don't mind my constant issues LOL

**Comment by Kodehawa** [comment]
ActiveTextColor=177,178,183,255

**Comment by vinceliuice** [comment]
OK! Thanks!
