### ISSUE TITLE
Qogir-dark-solid doesn't follow the correct text color.

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-kde#18]
Title. It was changed on 294fad29b7ad57778a422f3947f1ba7b5db6a60e then reverted only for Qogir-dark on c6af9dc43edb4f0dd53696853cf62835bd6e10f4, but you missed to revert the change in Qogir-dark-solid (Kvantum)

**Comment by vinceliuice** [comment]
No problem! I fixed this
