### ISSUE TITLE
panel字体的颜色好像有问题。

### ISSUE THREAD

**Issue by roxsky** [vinceliuice/Qogir-kde#19]
![2020-03-22_18-53](https://user-images.githubusercontent.com/4097168/77247695-79917680-6c6e-11ea-8ec8-d7532a0658bb.png)
我是从github上安装的，panel和上面的字体颜色都是黑色的，看起来怪怪的也很不清楚，我记得以前不是这样的，请问这个可以修复吗？

**Comment by vinceliuice** [comment]
你看下你颜色主题用的是不是light版本

**Comment by roxsky** [comment]
不是light的，是默认的qogir,只有dark版本没有这个问题。

Vince <notifications@github.com> 于2020年3月22日周日 下午7:04写道：

**Comment by vinceliuice** [comment]
好的，我检查一下出了什么问题

**Comment by roxsky** [comment]
麻烦你了，我再补充下信息
我是在archlinux里使用AUR包从github上安装的

Vince <notifications@github.com> 于2020年3月22日周日 下午9:09写道：

**Comment by vinceliuice** [comment]
不要用那个安装，那个不是我上传的现在没人维护了，我看了一下那个aur的脚本已经不一致了，你直接在这里下载安装吧

**Comment by roxsky** [comment]
好的，那我直接clone下去安装吧，谢谢拉。
