### ISSUE TITLE
Hardly distinguishable weather-overcast icon on light plasma theme

### ISSUE THREAD

**Issue by tonyfettes** [vinceliuice/Qogir-kde#22]
![Screenshot_20200506_004403](https://user-images.githubusercontent.com/29998228/81092206-dbfab980-8f32-11ea-9611-480fad6b8eb0.png)

As shown in the picture... It's too light to distinguish...But other weather related icons works well.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
Did you not use Qogir icon theme? this is a icon theme issue

**Comment by tonyfettes** [comment]
I've checked that I do use Qogir icon theme in my KDE system settings...
Anyway, thank you for your greate theme.

**Comment by vinceliuice** [comment]
Thank you! I'll check this

**Comment by tonyfettes** [comment]
Fixed.
