### ISSUE TITLE
Fix for Plasma 5.19

### ISSUE THREAD

**Issue by Slater91** [vinceliuice/Qogir-kde#23]
Plasma 5.19 introduces new features that require separator lines between elements in order for the themes to look good (see [here](https://pointieststick.com/2020/04/17/this-week-in-kde-our-cup-overfloweth-with-improvements/) for examples). Is this something that is going to be addressed with future releases of Qogir? It now looks quite frustratingly off without these new separators, especially with notifications.
I would be glad to do this on my own, but I do not have the slightest clue on how to do it.

Using KDE neon with Plasma 5.19.

**Comment by vinceliuice** [comment]
No problem! I'll update all my themes to support plasma 5.19

**Comment by Slater91** [comment]
That's great, thank you!

**Comment by Kodehawa** [comment]
Any news on this? D:

**Comment by vinceliuice** [comment]
I'll update this

**Comment by Slater91** [comment]
This was solved a while ago, thanks.
