### ISSUE TITLE
Kvantum: very big right-click menu shadow

### ISSUE THREAD

**Issue by Kodehawa** [vinceliuice/Qogir-kde#27]
The shadow for right-click menus on Kvantum seems to be way too big, at least inconsistent with the GTK theme shadow. Dunno if this is actually an issue, but this is *very* noticeable on a white bg: 
![image](https://user-images.githubusercontent.com/20606963/89754312-65c5a000-daa9-11ea-9668-988be3c37c4b.png)

Might be worth a look? Not sure, but thanks for looking into it :3

**Comment by vinceliuice** [comment]
I'll update this

**Comment by Kodehawa** [comment]
Okie, thanks you!

**Comment by Kodehawa** [comment]
Any news?

**Comment by Kodehawa** [comment]
Qogir-<variant>.kvconfig:

Change `menu_shadow_depth=6` to `menu_shadow_depth=2`

That makes it about similar to the GTK theme. Issue is that it's not really perfect, but I dunno how to play with the SVG file.
