### ISSUE TITLE
Aurorae theme issue

### ISSUE THREAD

**Issue by specialworld83** [vinceliuice/Qogir-kde#3]
Hello, unfortunately on kde setting in kglobals the aurorae engine is not displayed. The settings are set to use kwindecoration2

If instead you enter the plasma control panel by default the theme of the decorations breeze.

[org.kde.kdecoration2]
theme=__aurorae__svg__Qogir

**Comment by vinceliuice** [comment]
Yes, that's also problem to me, because I don't know how to make this right, I need wiki to help me make this works

**Comment by vinceliuice** [comment]
I finally know how to fix it now, you can download the last update, I fixed
