### ISSUE TITLE
弹出窗口的背景色好像不对

### ISSUE THREAD

**Issue by Hentioe** [vinceliuice/Qogir-kde#36]
例如在桌面上右键 - 新建文件夹，它是这个样子的：
![image](https://user-images.githubusercontent.com/13946976/123730228-a8ae8300-d8c8-11eb-9991-65edb47a7ceb.png)

在我印象里，曾经这类窗口的背景色和边框是一致的，或者没有这么明显的颜色反差。不知道是主题还是 kde 更新的关系，现在不对劲了。

**Comment by vinceliuice** [comment]
Solid 版本没事，普通版本窗口背景我加了透明度来显示模糊效果所以会这样
