### ISSUE TITLE
Weird color in settings when using Kvantum

### ISSUE THREAD

**Issue by freefreeno** [vinceliuice/Qogir-kde#4]
![Screenshot_20190616_032253](https://user-images.githubusercontent.com/41884680/59561449-248d4980-8fe6-11e9-9945-383dfc9b55df.png)

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by freefreeno** [comment]
@vinceliuice Well thank you for such a fast turn around. I use your themes to earn sometimes well a lot of the time. Also I had errors when running installer.
