### ISSUE TITLE
系统设置的按钮位置偏高

### ISSUE THREAD

**Issue by Firestar-Reimu** [vinceliuice/Qogir-kde#41]
![Screenshot_20220126_090635](https://user-images.githubusercontent.com/65082432/151086489-5be79024-40f4-4b11-8991-dcc5fb4bc743.png)

如图，“帮助”、“重置”、“应用”三个按钮的位置偏高，感觉是bug，应该如何调整？

使用的是 Qogir-Manjaro-Light KDE+Kvantum

**Comment by Firestar-Reimu** [comment]
![Screenshot_20220126_092134](https://user-images.githubusercontent.com/65082432/151087220-58010279-245b-4032-b280-bc0e63975941.png)

还有就是这里的图标偏左，应该不是字体问题吧？

**Comment by vinceliuice** [comment]
kvantum的bug，我修复不了

**Comment by Firestar-Reimu** [comment]
确实，把plasma样式从kvantum改成breeze可以解决按钮问题
