### ISSUE TITLE
Issue with SDDM theme

### ISSUE THREAD

**Issue by reyclo** [vinceliuice/Qogir-kde#8]
Hello,

I got an issue with a the SDDM theme and I don't know how to fix it. When I try to apply the SDDM theme i got the following error:

![image](https://user-images.githubusercontent.com/47411440/62550084-e97ef800-b869-11e9-8164-687c4251ea36.png)

Thank you for your time and your help.

**Comment by donitondo** [comment]
I fixed it by editing the /usr/share/sddm/themes/Qogir/components/Clock.qml file, changing the line `import QtQuick.Controls 2.5` for `import QtQuick.Controls 1.1`

**Comment by reyclo** [comment]
Thanks works great now!
